### ISSUE TITLE
Crash on Galaxy S4 Device

### ISSUE THREAD

**Issue by jffrymrtn** [jffrymrtn/writeily-pro#68]
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.writeily.pro/me.writeily.pro.NoteActivity}: java.lang.IllegalArgumentException: URI is not absolute: file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Fme.sheimi.sgit%2Ffiles%2Frepo%2FArticles%2Ftwst.md
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
    at android.app.ActivityThread.access$900(ActivityThread.java:161)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:157)
    at android.app.ActivityThread.main(ActivityThread.java:5356)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
    at dalvik.system.NativeStart.main(Native Method)
    Caused by: java.lang.IllegalArgumentException: URI is not absolute: file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Fme.sheimi.sgit%2Ffiles%2Frepo%2FArticles%2Ftwst.md
    at java.io.File.checkURI(File.java:220)
    at java.io.File.<init>(File.java:177)
    at me.writeily.pro.NoteActivity.getFileFromUri(NoteActivity.java:125)
    at me.writeily.pro.NoteActivity.readFileUriFromIntent(NoteActivity.java:137)
    at me.writeily.pro.NoteActivity.openFromEditAction(NoteActivity.java:110)
    at me.writeily.pro.NoteActivity.onCreate(NoteActivity.java:85)
    at android.app.Activity.performCreate(Activity.java:5431)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
    ... 11 more

**Comment by Minty123** [comment]
Odd, I habe an S4 AS well (using Google Edition Rom though...) and everything is fine for me. If I can help in any way, let me know!

**Comment by jffrymrtn** [comment]
@Minty123 Odd indeed. I'm not sure what caused the crash since it looks like he's opening from storage in the traditional way... I can't replicate it in any way...

**Comment by davydsantos** [comment]
To mimic the old behaviour we could catch any unexpected exception and return null as the file contents. This is going to make the user ser a blank page since no contente got loaded.

I haven't tried yet but input a wrong file name might be enough to replicate the bug.

I hate to do this kind of thing but it would, at first, hide the issue and make it not end unexpectedly.

**Comment by jffrymrtn** [comment]
From the error, it looks like the URI isn't even pointing to the "writeily" folder... Right now, even imported files open from the writeily folder (/emulated/data/writeily vs /emulated/data/me.sheimi.git/files).

I've only gotten one crash from this and I don't suspect many people use Sheimi or any kind of Git client on Android anyway. I'm hoping this'll be fixed after I implement #26 (where this user can then just point to the Git directory as the default).

I'll still try to replicate it as I test stuff, but don't think it's worth spending time fixing yet since it might fix itself soon
