### ISSUE TITLE
NPE if preview new created empty note

### ISSUE THREAD

**Issue by iptux** [jffrymrtn/writeily-pro#73]
1. click Floating Action Button
2. click Create Note Button
3. click Preview Button
4. app crash, log follows
```
E/AndroidRuntime(25968): FATAL EXCEPTION: main
E/AndroidRuntime(25968): Process: me.writeily.pro, PID: 25968
E/AndroidRuntime(25968): java.lang.RuntimeException: Unable to start activity ComponentInfo{me.writeily.pro/me.writeily.pro.PreviewActivity}: java.lang.NullPointerException
E/AndroidRuntime(25968): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
E/AndroidRuntime(25968): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
E/AndroidRuntime(25968): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime(25968): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
E/AndroidRuntime(25968): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(25968): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(25968): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime(25968): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(25968): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(25968): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime(25968): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime(25968): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime(25968): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(25968): Caused by: java.lang.NullPointerException
E/AndroidRuntime(25968): 	at me.writeily.pro.PreviewActivity.onCreate(PreviewActivity.java:46)
E/AndroidRuntime(25968): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime(25968): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime(25968): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
E/AndroidRuntime(25968): 	... 12 more
```

**Comment by jffrymrtn** [comment]
Thanks, fixed :)
